services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 admin admin123;
      mc mb local/datalake || true;
      mc anonymous set public local/datalake;
      exit 0;
      "

  spark:
    image: apache/spark:3.5.5
    container_name: spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      retries: 10
      start_period: 10s

  spark-worker:
    image: apache/spark:3.5.5
    depends_on:
      spark:
        condition: service_healthy
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077
    environment:
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_CORES: 1
    restart: unless-stopped

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: yes
      JUPYTER_TOKEN: "xxx"
    volumes:
      - ./notebooks:/home/jovyan/work
      - d:/docs:/data                    # ← D:\docs mounted as /data
    depends_on:
      - spark-worker

volumes:
  minio_data: